name: flutter_image_gallery
description: Application Flutter pour afficher les images depuis Symfony API

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.0.0
  url_launcher: ^6.2.5
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
